smithy-lang/smithy-gradle-plugin

README.md
build.gradle.kts
examples/adds-tags/build.gradle.kts
examples/disable-jar/build.gradle.kts
examples/failure-cases/invalid-projection/build.gradle.kts
examples/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/failure-cases/syntax-error/build.gradle.kts
examples/multiple-sources/build.gradle.kts
examples/projection/build.gradle.kts
examples/projects-with-tags/build.gradle.kts
examples/source-projection/build.gradle.kts
src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java

Work towards completing awslabs/smithy#104
This PR also contains a set of changes to depend on the `0.8.0` versions of Smithy packages.

Configure Gradle to publish plugin

---

build.gradle.kts

Update task construction to remove cycle

---

README.md
build.gradle.kts
examples/adds-tags/build.gradle.kts
examples/disable-jar/build.gradle.kts
examples/failure-cases/invalid-projection/build.gradle.kts
examples/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/failure-cases/syntax-error/build.gradle.kts
examples/multiple-sources/build.gradle.kts
examples/projection/build.gradle.kts
examples/projects-with-tags/build.gradle.kts
examples/source-projection/build.gradle.kts
src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java

Update version and Smithy dependencies

---

README.md
build.gradle.kts
examples/adds-tags/build.gradle.kts
examples/disable-jar/build.gradle.kts
examples/failure-cases/invalid-projection/build.gradle.kts
examples/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/failure-cases/syntax-error/build.gradle.kts
examples/multiple-sources/build.gradle.kts
examples/projection/build.gradle.kts
examples/projects-with-tags/build.gradle.kts
examples/source-projection/build.gradle.kts
src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java

Bump version to 0.3.1

---

README.md
build.gradle.kts
examples/adds-tags/build.gradle.kts
examples/disable-jar/build.gradle.kts
examples/failure-cases/invalid-projection/build.gradle.kts
examples/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/failure-cases/syntax-error/build.gradle.kts
examples/multiple-sources/build.gradle.kts
examples/projection/build.gradle.kts
examples/projects-with-tags/build.gradle.kts
examples/smithy-build-task/build.gradle.kts
examples/source-projection/build.gradle.kts

Update to 0.4.1

---

README.md
src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java

Fix remaining version references

---

README.md
build.gradle.kts
examples/adds-tags/build.gradle.kts
examples/disable-jar/build.gradle.kts
examples/failure-cases/invalid-projection/build.gradle.kts
examples/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/failure-cases/syntax-error/build.gradle.kts
examples/multi-project/consumer/build.gradle.kts
examples/multiple-sources/build.gradle.kts
examples/projection/build.gradle.kts
examples/projects-with-tags/build.gradle.kts
examples/smithy-build-task/build.gradle.kts
examples/source-projection/build.gradle.kts

Update to 0.4.3

---

CHANGELOG.md

Bump to 0.5.1

---

src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildJar.java

Use System's path separator for classpaths

---

config/checkstyle/checkstyle.xml

Fix Checkstyle to work on Windows

---

CHANGELOG.md
README.md
build.gradle.kts
examples/adds-tags/build.gradle.kts
examples/disable-jar/build.gradle.kts
examples/failure-cases/invalid-projection/build.gradle.kts
examples/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/failure-cases/syntax-error/build.gradle.kts
examples/multi-project/consumer/build.gradle.kts
examples/multiple-sources/build.gradle.kts
examples/no-models/build.gradle.kts
examples/projection/build.gradle.kts
examples/projects-with-tags/build.gradle.kts
examples/scans-for-cli-version/build.gradle.kts
examples/smithy-build-task/build.gradle.kts
examples/source-projection/build.gradle.kts

Bump version to 0.5.2

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Remove CLA line from CONTRIBUTING.md

---

examples/adds-tags/README.md
examples/adds-tags/build.gradle.kts
examples/adds-tags/settings.gradle.kts
examples/disable-jar/README.md
examples/disable-jar/settings.gradle.kts
examples/failure-cases/README.md
examples/failure-cases/invalid-projection/settings.gradle.kts
examples/failure-cases/missing-runtime-dependency/settings.gradle.kts
examples/failure-cases/syntax-error/settings.gradle.kts
examples/multi-project/README.md
examples/multi-project/settings.gradle.kts
examples/multiple-sources/README.md
examples/multiple-sources/settings.gradle.kts
examples/no-models/README.md
examples/no-models/settings.gradle.kts
examples/output-directory-with-projection/README.md
examples/output-directory-with-projection/settings.gradle.kts
examples/output-directory/README.md
examples/output-directory/settings.gradle.kts
examples/projection/README.md
examples/projection/settings.gradle.kts
examples/projects-with-tags/README.md
examples/projects-with-tags/settings.gradle.kts
examples/scans-for-cli-version/README.md
examples/scans-for-cli-version/settings.gradle.kts
examples/smithy-build-task/README.md
examples/smithy-build-task/settings.gradle.kts
examples/source-projection/README.md
examples/source-projection/settings.gradle.kts

This adds READMEs to each of the examples explaining what they do, how to use them as a starting point, and providing links to relevant documentation.

Update example documentation

---

README.md

Fix ci badge link

---

CHANGELOG.md
README.md
build.gradle.kts
examples/adds-tags/build.gradle.kts
examples/disable-jar/build.gradle.kts
examples/failure-cases/invalid-projection/build.gradle.kts
examples/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/failure-cases/syntax-error/build.gradle.kts
examples/multi-project/consumer/build.gradle.kts
examples/multiple-sources/build.gradle.kts
examples/no-models/build.gradle.kts
examples/output-directory-with-projection/build.gradle.kts
examples/output-directory/build.gradle.kts
examples/projection/build.gradle.kts
examples/projects-with-tags/build.gradle.kts
examples/scans-for-cli-version/build.gradle.kts
examples/smithy-build-task/build.gradle.kts
examples/source-projection/build.gradle.kts

Bump version to 0.6.0

---

src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuild.java
src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildJar.java

This plugin has two tasks that produce output, `SmithyBuild` and
`SmithyBuildJar`. Both of these tasks model their outputs as a
`java.io.File`, which results in a few problems:
1. The output locations are eagerly evaluated, which can introduce race
conditions if output locations are overridden through the task itself
or the `SmithyExtension`
2. Gradle cannot track which tasks are responsible for producing which
collections of Smithy files, which means that explicit dependencies
may need to be introduced by calling `dependsOn`
This commit leaves the current APIs in place for compatibility and adds
new ones that support lazy configuration and implicit task dependency
tracking. For more information on these Gradle features, see:
* https://docs.gradle.org/current/userguide/lazy_configuration.h …

Support implicit dependencies

---

build.gradle.kts
config/checkstyle/checkstyle.xml
gradle/wrapper/gradle-wrapper.properties
smithy-gradle-plugin/build.gradle.kts

Upgrades the gradle version used in the project to gradle 8

Upgrade to gradle 8

---

build.gradle.kts
integ-test-utils/build.gradle.kts
integ-test-utils/src/main/java/software/amazon/smithy/gradle/Utils.java
settings.gradle.kts

Adds a common integration test utils package so that we can share integration testing logic across multiple plugin packages.

Add common integration test utils package

---

examples/adds-tags/settings.gradle.kts
examples/disable-jar/settings.gradle.kts
examples/failure-cases/invalid-projection/settings.gradle.kts
examples/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/failure-cases/missing-runtime-dependency/settings.gradle.kts
examples/failure-cases/require-prerequisite-plugin/settings.gradle.kts
examples/failure-cases/syntax-error/settings.gradle.kts
examples/includes-in-sourceset/settings.gradle.kts
examples/multi-project/settings.gradle.kts
examples/multiple-sources/settings.gradle.kts
examples/no-models/settings.gradle.kts
examples/output-directory-with-projection/build.gradle.kts
examples/output-directory-with-projection/settings.gradle.kts
examples/output-directory/build.gradle.kts
examples/output-directory/settings.gradle.kts
examples/projects-with-tags/build.gradle.kts
examples/projects-with-tags/settings.gradle.kts
examples/scans-for-cli-version/settings.gradle.kts
examples/smithy-build-task/settings.gradle.kts
examples/source-projection-jar/settings.gradle.kts
examples/source-projection/settings.gradle.kts
smithy-gradle-plugin/src/it/java/software/amazon/smithy/gradle/SourceProjectionTest.java
smithy-jar-plugin/src/it/java/software/amazon/smithy/gradle/SourceProjectionJarTest.java

Applies all changes expected that should have been included in: https://github.com/smithy-lang/smithy-gradle-plugin/pull/87

[Fix] Allow use of latest local or remote smithy dependencies for all integ 

---

build.gradle.kts
smithy-base-plugin/build.gradle.kts
smithy-jar-plugin/build.gradle.kts

Fixes two issues discovered during first publishing attempt

Add plugin description

---

buildSrc/src/main/kotlin/smithy-gradle-plugin.plugin-conventions.gradle.kts

Adds configuration needed for publishing maven artifact

Add missing licensing and signing configuration

---

.github/PULL_REQUEST_TEMPLATE.md

* Updates the PR template.
* This PR update will hopefully improve the quality of PR descriptions, making changes easier to review and making changelogs easier to write.
* This PR uses the updated template.
* Corresponding Smithy repo change [here](https://github.com/smithy-lang/smithy/pull/2102)
---

Update PR template to be more descriptive

---

smithy-jar/src/main/java/software/amazon/smithy/gradle/SmithyJarPlugin.java

Updates the `smithy-jar` plugin to add the staged smithy sources to the compile classpath. This allows users to easily apply an annotation processor that picks up staged smithy models. For example a trait-codegen annotation processor could generate trait definitions from staged smithy models to include in the output jar.
Previously a user would have had to add the following to their gradle build script in order to run an annotation processor that can pick up staged smithy sources.
``` groovy
sourceSets {
main {
java {
compileClasspath += main.resources.sourceDirectories
}
}
}
```
I created temporary test project with an annotation processor based on the linked commit and tested that the processor could discover the staged models.
* Smithy annotation processor: …

Update JAR plugin to add smithy resources to compile classpath

---

README.md
examples/base-plugin/failure-cases/conflicting-output-dir-configs/build.gradle.kts
examples/base-plugin/failure-cases/forbid-dependency-resolution-fork/build.gradle.kts
examples/base-plugin/failure-cases/forbid-dependency-resolution-no-fork/build.gradle.kts
examples/base-plugin/includes-in-sourceset/build.gradle.kts
examples/base-plugin/output-directory-config/build.gradle.kts
examples/base-plugin/output-directory-with-projection/build.gradle.kts
examples/base-plugin/output-directory/build.gradle.kts
examples/base-plugin/scans-for-cli-version/build.gradle.kts
examples/base-plugin/smithy-build-task/build.gradle.kts
examples/jar-plugin/adds-tags/build.gradle.kts
examples/jar-plugin/build-dependencies/internal-model/build.gradle.kts
examples/jar-plugin/build-dependencies/service/build.gradle.kts
examples/jar-plugin/custom-trait/consumer/build.gradle.kts
examples/jar-plugin/custom-trait/custom-string-trait/build.gradle.kts
examples/jar-plugin/disable-jar/build.gradle.kts
examples/jar-plugin/failure-cases/invalid-projection/build.gradle.kts
examples/jar-plugin/failure-cases/missing-runtime-dependency/build.gradle.kts
examples/jar-plugin/kotlin-jvm-project/build.gradle.kts
examples/jar-plugin/multi-project/consumer/build.gradle.kts
examples/jar-plugin/multiple-jars/build.gradle.kts
examples/jar-plugin/multiple-sources/build.gradle.kts
examples/jar-plugin/no-models/build.gradle.kts
examples/jar-plugin/projection/build.gradle.kts
examples/jar-plugin/projects-with-tags/build.gradle.kts
examples/jar-plugin/scala-project/build.gradle.kts
examples/jar-plugin/source-projection/build.gradle.kts

* Updates versions to `0.10.1` in examples using the `sync-versions` script
---

sync version

---

bin/sync-version.sh
examples/trait-package-plugin/create-simple-trait/build.gradle.kts
examples/trait-package-plugin/use-with-existing-trait/build.gradle.kts

Updates the version sync script to handle multiple `-` so the trait plugin will be correctly updated.
Also updates build scripts in trait package plugin to use the same convention as other build scripts so the version is discoverable.
---

Update version sync script

---

.github/workflows/ci.yml

Adds JDK 17 to testing matrix.
* See workflow running on this PR. 
---

Add JDK 17 to test matrix
