smithy-lang/smithy-gradle-plugin

- README.md
- examples/adds-tags/build.gradle.kts
- examples/disable-jar/build.gradle.kts
- examples/failure-cases/invalid-projection/build.gradle.kts
- examples/failure-cases/missing-runtime-dependency/build.gradle.kts
- examples/failure-cases/syntax-error/build.gradle.kts
- examples/multiple-sources/build.gradle.kts
- examples/projection/build.gradle.kts
- examples/projects-with-tags/build.gradle.kts
- examples/source-projection/build.gradle.kts
- src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java
This commit automatically applies the java plugin and removes the need
for Smithy model projects to apply the java plugin.
> Apply java plugin automatically

- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
The Gradle plugin previously optimized for fast startup, but this came
at the expense of more demanding long-running tasks like building large
models. This change disables capping the maximum JIT level so that more
optimizations can be made. This resulted in a reduction from ~17secs to
~11 seconds for large model builds.
> Remove the disabling of more in-depth JIT

- src/main/java/software/amazon/smithy/gradle/SmithyExtension.java
- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildJar.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyCliTask.java
Rather than always run in a process, this change allows the Smithy CLI
to be run in a thread using a custom class loader. This will probably
work in every case, but just in case, I added an option to force the CLI
to run in a separate process using the "fork" option.
On my machine, this change had the effect of shaving on ~1 second of time to
run a normal build. You also get much better stack traces when something
goes wrong since it's not run in a different process.
> Run CLI in thread by default

- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
This commit closes the URLClassLoader to close any outstanding loaded
JARs and help mitigate any java.util.zip.ZipException exceptions.
> Close the URLClasserLoader

- build.gradle.kts
- examples/adds-tags/build.gradle.kts
- examples/disable-jar/build.gradle.kts
- examples/failure-cases/invalid-projection/build.gradle.kts
- examples/failure-cases/missing-runtime-dependency/build.gradle.kts
- examples/failure-cases/syntax-error/build.gradle.kts
- examples/multi-project/build.gradle.kts
- examples/multi-project/consumer/build.gradle.kts
- examples/multi-project/consumer/model/main.smithy
- examples/multi-project/gradle.properties
- examples/multi-project/producer1/build.gradle.kts
- examples/multi-project/producer1/src/main/java/software/amazon/smithy/producer1/Producer1Trait.java
- examples/multi-project/producer1/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
- examples/multi-project/producer1/src/main/resources/META-INF/smithy/main.smithy
- examples/multi-project/producer1/src/main/resources/META-INF/smithy/manifest
- examples/multi-project/producer2/build.gradle.kts
- examples/multi-project/producer2/src/main/java/software/amazon/smithy/producer2/Producer2Trait.java
- examples/multi-project/producer2/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
- examples/multi-project/producer2/src/main/resources/META-INF/smithy/main.smithy
- examples/multi-project/producer2/src/main/resources/META-INF/smithy/manifest
- examples/multi-project/settings.gradle.kts
- examples/multiple-sources/build.gradle.kts
- examples/projection/build.gradle.kts
- examples/projects-with-tags/build.gradle.kts
- examples/smithy-build-task/build.gradle.kts
- examples/source-projection/build.gradle.kts
- src/it/java/software/amazon/smithy/gradle/Utils.java
- src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java
- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
Smithy needs to run after compileJava so that dependencies in the same
project are built first. It also needs to run before processResources so
that artifacts created by Smithy are considered part of the generated
JAR.
This has been tested using the integration tests in this package as well
as using the awslabs/smithy repo with various states (clean build and
cleaning individual projects).
> Fix build graph issue

- src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java
- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
- src/main/java/software/amazon/smithy/gradle/tasks/BaseSmithyTask.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuild.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildJar.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyCliTask.java
- src/main/java/software/amazon/smithy/gradle/tasks/Validate.java
This commits makes many changes to the Gradle plugin to address the
following issues:
1. Fixes writing to stderr and stdout from Smithy CLI. Writing to
stdout and stderr was really inconsistent in whether or not
it's able to reroute writing to stdout to it's logging machinery.
This might be because Smithy makes use of threads within a task,
not sure. To workaround this, I've updating the Smithy CLI to
instead of writing directly to stdout, invokes a customizable
Consumer<String>. The Gradle plugin changes this to instead
directly log a warning message. This works every time.
2. Fixes build order and dependencies of building the Smithy model
and validating the model. There was a lot that changed here,
including how tasks are created, referenced, and ordered.
3. The Gradle plugin now uses …
> Make fixes to Gradle dependencies and output

- README.md
- build.gradle.kts
- examples/adds-tags/build.gradle.kts
- examples/disable-jar/build.gradle.kts
- examples/failure-cases/invalid-projection/build.gradle.kts
- examples/failure-cases/missing-runtime-dependency/build.gradle.kts
- examples/failure-cases/missing-runtime-dependency/model/main.smithy
- examples/failure-cases/syntax-error/build.gradle.kts
- examples/multi-project/consumer/build.gradle.kts
- examples/multi-project/producer1/build.gradle.kts
- examples/multi-project/producer2/build.gradle.kts
- examples/multiple-sources/build.gradle.kts
- examples/projection/build.gradle.kts
- examples/projection/model/main.smithy
- examples/projects-with-tags/build.gradle.kts
- examples/smithy-build-task/build.gradle.kts
- examples/source-projection/build.gradle.kts
- examples/source-projection/model/main.smithy
- src/it/java/software/amazon/smithy/gradle/ProjectsWithTagsTest.java
- src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java
This commit updates the Smithy Gradle Plugin to use the GA release
of Smithy. It updates for a few breaking changes in addition to the
dependency and versioning updates.
> Version 0.5.0 for Smithy 1.0.0 release

- build.gradle.kts
Updates com.gradle.plugin-publish plugin to version 0.11.0
> Update Gradle publish plugin to 0.11.0

- examples/output-directory-with-projection/build.gradle.kts
- examples/output-directory-with-projection/model/main.smithy
- examples/output-directory-with-projection/settings.gradle.kts
- examples/output-directory-with-projection/smithy-build.json
- examples/output-directory/build.gradle.kts
- examples/output-directory/model/main.smithy
- examples/output-directory/settings.gradle.kts
- examples/output-directory/smithy-build.json
- src/it/java/software/amazon/smithy/gradle/OutputDirectoryTest.java
- src/it/java/software/amazon/smithy/gradle/OutputDirectoryWithProjectionTest.java
- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
Currently, if an `outputDirectory` [extension property](https://awslabs.github.io/smithy/1.0/guides/building-models/gradle-plugin.html#smithy-extension-properties) has been configured, the `smithyBuildJar` task will not resolve the correct projection plugin path.  If a projection has been configured, a GradleException will be thrown, however, if no projection is configured and the `sources` plugin is being used, only a warning will be emitted.  This CR updates the resolution of the plugin path when an `outputDirectory` has been configured.
> Use outputDirectory to resolve plugin path

- .github/workflows/ci.yml
- README.md
Adds CI using GitHub actions. Since none of this takes effect until some variant of actions is already in the main branch, here's a pr on my fork demonstrating it in action: https://github.com/JordonPhillips/smithy-gradle-plugin/pull/1
> Add github actions ci

- config/checkstyle/checkstyle.xml
Update checkstyle to allow 2021 copyright
n.b. checkstyle was never updated to allow 2020 copyright.  This is set to accept 2019 and 2021, but not 2020, as no headers should use 2020.
> Update checkstyle to allow 2021 copyright

- .github/workflows/ci.yml
- CONTRIBUTING.md
This PR updates references to the branch so that main can be used the default branch on this repository.
> Refer to main branch

- CHANGELOG.md
- README.md
- build.gradle.kts
- examples/adds-tags/build.gradle.kts
- examples/disable-jar/build.gradle.kts
- examples/failure-cases/invalid-projection/build.gradle.kts
- examples/failure-cases/missing-runtime-dependency/build.gradle.kts
- examples/failure-cases/syntax-error/build.gradle.kts
- examples/multi-project/consumer/build.gradle.kts
- examples/multiple-sources/build.gradle.kts
- examples/no-models/build.gradle.kts
- examples/output-directory-with-projection/build.gradle.kts
- examples/output-directory/build.gradle.kts
- examples/projection/build.gradle.kts
- examples/projects-with-tags/build.gradle.kts
- examples/scans-for-cli-version/build.gradle.kts
- examples/smithy-build-task/build.gradle.kts
- examples/source-projection/build.gradle.kts
- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
Fixed the `ZipFile invalid LOC header (bad signature)` error that was
caused by changing resource files. This was fixed by disabling
URLConnection caching globally with URLConnection#setDefaultUseCaches
to false.
> Fix ZipFile signature issue

- CHANGELOG.md
Updates changelog with changes for `0.5.3`.
> Bump version to 0.5.3

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java
This commit upgrades Gradle to 7.1 so that we can build it with newer
version of Java, and it fixes a new issues that cropped up as a result where
files being placed into a JAR in one of the integration tests started failing
due to duplicates.
Closes #42
> Upgrade Gradle to 7.1 and fix duplicate JAR entry

- src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildJar.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyTagsTask.java
https://github.com/awslabs/smithy-gradle-plugin/issues/46
As described in the issue, Smithy-Tags logic doesn't run the 2nd time. So this change separate Smithy-Tags logic into a separate Task. So that it is always run before the Jar Task.
*Testing:*
With this change, running `gradle jar -info` the 2nd time shows:
```
> Task :smithyBuildJar UP-TO-DATE
Caching disabled for task ':smithyBuildJar' because:
Build cache is disabled
Skipping task ':smithyBuildJar' as it is up-to-date.
:smithyBuildJar (Thread[Execution worker for ':',5,main]) completed. Took 0.009 secs.
:processResources (Thread[Execution worker for ':',5,main]) started.
> Task :processResources UP-TO-DATE
file or directory …
```
> Separate Smithy-Tags into separate Task

- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
closes https://github.com/awslabs/smithy-gradle-plugin/issues/51
Use the actual project build directory rather than hard coding it to `projectDir/build`. 
I haven't tested this locally but I'm assuming the integration tests would catch any issues with this kind of change.
> Fix buildDir not being respected

- build.gradle.kts
- src/it/java/software/amazon/smithy/gradle/AddsTagsTest.java
- src/it/java/software/amazon/smithy/gradle/DisableJarTest.java
- src/it/java/software/amazon/smithy/gradle/InvalidProjectionTest.java
- src/it/java/software/amazon/smithy/gradle/MissingRuntimeDependencyTest.java
- src/it/java/software/amazon/smithy/gradle/MultipleSourcesTest.java
- src/it/java/software/amazon/smithy/gradle/NoModelsTest.java
- src/it/java/software/amazon/smithy/gradle/OutputDirectoryTest.java
- src/it/java/software/amazon/smithy/gradle/OutputDirectoryWithProjectionTest.java
- src/it/java/software/amazon/smithy/gradle/ProjectionTest.java
- src/it/java/software/amazon/smithy/gradle/ProjectsWithTagsTest.java
- src/it/java/software/amazon/smithy/gradle/ScansForCliVersionTest.java
- src/it/java/software/amazon/smithy/gradle/SmithyBuildTaskTest.java
- src/it/java/software/amazon/smithy/gradle/SourceProjectionTest.java
- src/it/java/software/amazon/smithy/gradle/SyntaxErrorTest.java
When tests failed in GitHub actions, we had no output to act on. This
change ensures that stderr/stdout are printed by each integration test,
and then uses a logging plugin to dump out this captured output on
failure so we can, ya know, understand how to fix weird platform
specific issues if they come up in integration tests.
> Make failed tests something we can actually fix

- src/it/java/software/amazon/smithy/gradle/DisableJarTest.java
- src/it/java/software/amazon/smithy/gradle/SmithyBuildTaskTest.java
- src/it/java/software/amazon/smithy/gradle/Utils.java
- src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildJar.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyCliTask.java
The Smithy CLI was updated to change some of its output, and remove
harder to test behaviors (like using a global variable to determine
where to send output). This commit updates the Gradle plugin to work
with these updates, but the plugin will also continue to work with older
versions of the CLI too.
> Update Gradle plugin to work with new Smithy CLI

- src/it/java/software/amazon/smithy/gradle/ProjectionTest.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyCliTask.java
The Smithy CLI supports --debug, --logging, and --stacktrace parameters. This commit updates the Gradle pluging to pass these arguments through to the CLI if they were provided to Gradle. All versions of the Smithy CLI support these arguments after 1.0, so this is a safe change regardless of the resolved CLI version.
> Pass logging, debug, and stacktrace params to CLI

- src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java
Version detection text isn't really needed unless you're troubleshooting, and the messaging around needing an explicit dependency if publishing a JAR can be confusing. You can now see this info using --info instead.
> Make Smithy version detection info

- src/it/java/software/amazon/smithy/gradle/ProjectionTest.java
https://github.com/awslabs/smithy/pull/1526 updated the logging in the ValidateCommand, changing from `"Validating Smithy model sources"` to `"Smithy validation complete"`, breaking the modifiesLogging integration test. This fixes the test with the updated logging string.
> Fix modifiesLogging test

- build.gradle.kts
- config/spotbugs/filter.xml
*Issue #, if available:* related to #56 (although doesnt resolve)
Updates Dependencies to resolve issues with configuration caching as well as a few other minor warnings.
Also removes the src and javadoc jars from the definition as these are added automatically in the newer versions of the com.gradle.plugin-publish plugin.
*Testing* 
Ran `./gradlew --configuration-cache build` and did not have any errors.
> Update dependencies 

- src/main/java/software/amazon/smithy/gradle/SmithyPlugin.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuild.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildJar.java
- src/main/java/software/amazon/smithy/gradle/tasks/SmithyTagsTask.java
Issue #72
Configures the tasks to have their first configuration action to be copying the value from the extension to the task.
> Correclty bind extension to tasks (#72)

- src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildJar.java
The other methods that set this property are deprecated, so it seems an oversight that this method is package private.
> Make SmithyBuildJar.getOutputDir() public

- examples/jar-plugin/multi-project/consumer/build.gradle.kts
- examples/jar-plugin/multi-project/producer1/src/main/java/software/amazon/smithy/producer1/Producer1Trait.java
- examples/jar-plugin/multi-project/producer2/src/main/java/software/amazon/smithy/producer2/Producer2Trait.java
- examples/jar-plugin/multi-project/settings.gradle.kts
- smithy-jar-plugin/src/it/java/software/amazon/smithy/gradle/MultiProjectTest.java
Corrects the multi-project example to use the new `smithy-jar` plugin and the `AnnotationTrait` class instead of `BooleanTrait`. The previous version of the gradle-plugin did not have an integration test for the multi-project example, so this PR also adds an integration test for the jar plugin using the multi-project example. 
> Fix multi-project example and add integration test

- examples/base-plugin/output-directory-with-projection/build.gradle.kts
- smithy-templates.json
Adds a `smithy-templates.json` file to the repository so examples can be copied using the `smithy init` CLI tool.
> Add smithy-templates file

- README.md
- bin/sync-version.sh
- examples/base-plugin/failure-cases/conflicting-output-dir-configs/build.gradle.kts
- examples/base-plugin/failure-cases/forbid-dependency-resolution-fork/build.gradle.kts
- examples/base-plugin/failure-cases/forbid-dependency-resolution-no-fork/build.gradle.kts
- examples/base-plugin/includes-in-sourceset/build.gradle.kts
- examples/base-plugin/output-directory-config/build.gradle.kts
- examples/base-plugin/output-directory-with-projection/build.gradle.kts
- examples/base-plugin/output-directory/build.gradle.kts
- examples/base-plugin/scans-for-cli-version/build.gradle.kts
- examples/base-plugin/smithy-build-task/build.gradle.kts
- examples/jar-plugin/adds-tags/build.gradle.kts
- examples/jar-plugin/build-dependencies/internal-model/build.gradle.kts
- examples/jar-plugin/build-dependencies/service/build.gradle.kts
- examples/jar-plugin/custom-trait/consumer/build.gradle.kts
- examples/jar-plugin/custom-trait/custom-string-trait/build.gradle.kts
- examples/jar-plugin/disable-jar/build.gradle.kts
- examples/jar-plugin/failure-cases/invalid-projection/build.gradle.kts
- examples/jar-plugin/failure-cases/missing-runtime-dependency/build.gradle.kts
- examples/jar-plugin/failure-cases/require-prerequisite-plugin/build.gradle.kts
- examples/jar-plugin/kotlin-jvm-project/build.gradle.kts
- examples/jar-plugin/multi-project/consumer/build.gradle.kts
- examples/jar-plugin/multiple-jars/build.gradle.kts
- examples/jar-plugin/multiple-sources/build.gradle.kts
- examples/jar-plugin/no-models/build.gradle.kts
- examples/jar-plugin/projection/build.gradle.kts
- examples/jar-plugin/projects-with-tags/build.gradle.kts
- examples/jar-plugin/source-projection/build.gradle.kts
- smithy-base-plugin/build.gradle.kts
- smithy-jar-plugin/build.gradle.kts
Gradle requires plugins ID's to be namespaced. 
This PR updates the plugin ids to use the `software.amazon.smithy.gradle` namespace.
> Add namespace to plugin ids

- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/SmithyBasePlugin.java
- smithy-jar-plugin/src/main/java/software/amazon/smithy/gradle/SmithyJarPlugin.java
Updates the ordering of tasks so that: 
1. The Format task executes before the build task. This ensures any files written to an output jar will be formatted. 
2. Updates to create a dependency for the compile task on `processResources`. This ensures that smithy output files are in the META-INF/ output folder before the compile task is executed so they are available to the compile task for any annotation processors.
The following is an example of the new task order for the `quickstart gradle` template (using --dry-run)
```
:smithyFormat SKIPPED
:smithyBuild SKIPPED
:smithyJarStaging SKIPPED
:processResources SKIPPED
:compileJava SKIPPED
:classes SKIPPED
:jar SKIPPED
:assemble SKIPPED
:compileTestJava SKIPPED
:smithyJarValidate SKIPPED
:processTestResources SKIPPED
:testClasses SKIPPED …
```
> Update task ordering

- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/SmithyBasePlugin.java
- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/internal/CliDependencyResolver.java
*Issue #, if available:* 
fixes https://github.com/smithy-lang/smithy/issues/1297
Updates the resolution of the `smithy-cli` dependency to use the resolved version of `smithy-model` dependencies from the runtime configuration. This prevents the cli version from being resolved to a a higher version than the project can support.
Created a project with the following dependencies (following the project in the linked issue): 
```
dependencies {
implementation("software.amazon.smithy:smithy-model:[1.17.0, 2.0[")
implementation("software.amazon.smithy.typescript:smithy-typescript-codegen:0.11.0")
}
```
The resolved dependencies ended up with the smithy-cli version being `1.39.0` which is the latest CLI version and does not match the required smithy-model version that is resolved. 
Resolved …
> Resolve cli version from resolved runtime dependencies

- examples/base-plugin/smithy-build-task/smithy-build.json
- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/SmithyExtension.java
Issue #, if available:
Fixes #108
Updates to use the `.parseJsonWithComments` method to correctly handle comments in `smithy-build.json` files. Also adds a comment to a build file in the integration tests to prevent regressions. 
> Update to use correct parsing method to handle comments in build json

- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildTask.java
Issue #, if available: https://github.com/smithy-lang/smithy-gradle-plugin/issues/109
Updates the config file parameter to use `InputFiles` instead of `Input` to ensure changes to build configs trigger incremental build.
> Update to use InputFiles for build config parameter

- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
*Issue #, if available:* issue #113
Updates guard within `getProjectionPluginPath` utility function to allow for path resolution when file does not yet exist. 
> Update to allow for resolution when file does not exist yet

- build.gradle.kts
- config/checkstyle/checkstyle.xml
- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/SmithyBasePlugin.java
- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/internal/CliDependencyResolver.java
- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/tasks/AbstractSmithyCliTask.java
- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/tasks/BaseSmithyTask.java
- smithy-base-plugin/src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildTask.java
Silences the xdoclint warnings to reduce the amount of noise and updates a few javadoc comments.
> Update javadocs and reduce noise from doclint warnings

- examples/base-plugin/smithy-build-task/build.gradle.kts
- smithy-base/src/it/java/software/amazon/smithy/gradle/SmithyBuildTaskTest.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/SmithyBasePlugin.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/internal/CliDependencyResolver.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/AbstractSmithyCliTask.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/BaseSmithyTask.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildTask.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/SmithyFormatTask.java
- smithy-jar/src/main/java/software/amazon/smithy/gradle/tasks/SmithyValidateTask.java
1. Corrects an issue where the conventions set for the smithyBuildtask were causing custom defined tasks used without the java plugin applied to fail. The failure was due to the conventions not lazily executing the pulling of the configurations used for each of the classpaths. 
2. As part of fixing the above it was nicer to move the smithyCli config to always be created whenever the base plugin is applied even if no source sets are created. This allows users to apply the base plugin to resolve the cli artifact without needing to pass in a custom classpath with the CLI on it to the build task.
3. Applies some simple cleanup and renames the "RuntimeClasspath" parameter to "ModelDiscoveryClasspath" parameter for clarity for users using the build task on its own.
By …
> Move smithyCli configuration and correct issue with conventions

- smithy-templates.json
* Updates template descriptions to fill in empty descriptions and correct typos.
* N/A
---
> Touch up smithy-template.json descriptions

- smithy-base/src/main/java/software/amazon/smithy/gradle/SmithyBasePlugin.java
* Removes a check that compared resolved CLI version to minimum required for Smithy format task.
* Integ tests passed. No additional checks were added. 
---
> Remove check for CLI version before executing format

- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/BaseSmithyTask.java
* Currently if the gradle `--quiet` option is set then the gradle build and validate tasks will still print validation events that are non-breaking. 
* This PR updates the `quiet` setting in the gradle plugins to use apply the `--quiet` flag to the CLI command so that non-breaking validation events are not printed
* Executed `gradle build --quiet` with examples and confirmed no validation events were printed to build logs.
---
> Add quiet option when gradle quiet flag set

- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/BaseSmithyTask.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildTask.java
- smithy-jar/src/main/java/software/amazon/smithy/gradle/tasks/SmithyValidateTask.java
Adds a property to set the severity of validators for the `validate` and `build` tasks.
The default severity for the build task remains `WARNING` while the default for the `jarValidate` task is updated to `ERROR`. This prevents the double-printing of warning events during the build so that by default the jarValidate task only prints validation events that would have caused it to fail.
Note: not all smithy-cli commands have a `severity` option.
Executed a build with and without this change and confirmed the 
```
> Task :service:smithyFormat
Running smithy format
> Task :service:smithyBuild
Running smithy build
──  WARNING  ──────────────────────────────────────────────────────────── DocUrl
Shape: com.example.cafe.service#Order
File: …
```
> Add severity option for validators

- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/SmithyValidateTask.java
- smithy-jar/src/main/java/software/amazon/smithy/gradle/SmithyJarPlugin.java
* Moves the validate task to the base plugin and changes the Sources property to be `Sources` instead of `JarToValidate` as this task could be used to validate any set of smithy sources.
* The validate task is more generally useful that just for validating a JAR file in the smithy-jar plugin. Eventually we plan to add validation reports to this task which might be added as part of the base plugin. Because this task can be used outside of a jar context it should not live in the smithy-jar plugin.
* Executed integration tests which already test validation capability
---
> Move validate task to base plugin

- README.md
The current link https://smithy.io/2.0/guides/building-models/gradle-plugin.html goes to https://smithy.io/2.0/guides/gradle-plugin.html which seems to be able for 0.6.0 version. Updated the link to latest.
* Looked at the new rendered README and clicked the link to verify it is as expected.
---
> Update link to smithy.io docs for the plugin

- buildSrc/build.gradle.kts
- examples/jar-plugin/kotlin-jvm-project/build.gradle.kts
- settings.gradle.kts
- smithy-base/src/main/java/software/amazon/smithy/gradle/SmithyUtils.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/internal/CliDependencyResolver.java
- smithy-trait-package/build.gradle.kts
- smithy-trait-package/src/main/java/software/amazon/smithy/gradle/SmithyTraitPackagePlugin.java
Creates a new gradle plugin for quickly defining a smithy trait package. This plugin adds trait codegen to the 
smithyBuild dependencies if it does not already exist. The output of the trait codegen plugin is then added to the main java sourceset.  
Next steps: 
- Add a task to merge service provider files so existing traits can also live in the package.
- Add integration tests
- Possibly have the plugin auto-wire the smithy-model dependency
Manually tested with a local package. 
Additional tests will be added as part of the next steps and will require some additional setup.
---
> Add a new plugin for setting up a trait package

- examples/base-plugin/smithy-build-task/build.gradle.kts
- smithy-base/src/it/java/software/amazon/smithy/gradle/SmithyBuildTaskTest.java
- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/SmithyBuildTask.java
Currently, the standardized method to resolve a given projection + plugin's path is via the `SmithyExtension` method `getPluginProjectionPath`.  This method will return a `Provider<Path>` based on the `outputDirectory` property defined in the extension.
This pull request adds a similar convenience method on the SmithBuildTask implementation itself.  The referenced location is functionally the same in most normal setups.  In Gradle, utilizing a provider that is based off of the task implementation's `DirectoryProperty` instead of the extension's `DirectoryProperty`, even if the task's instance is bound to the extension's instance, will express the implicit dependency between task definitions.
That is, running `./gradlew copyOutput` on this task implementation will not execute the …
> Add convinence method which allows resolving plugin projection directories from SmithyBuild task instances

- README.md
- examples/trait-package-plugin/use-with-existing-trait/build.gradle.kts
- smithy-templates.json
- smithy-trait-package/src/main/java/software/amazon/smithy/gradle/SmithyTraitPackagePlugin.java
Adds documentation for the `smithy-trait-package` plugin including: 
1. Readme entries
2. Update examples descriptions
3. Updates to `smithy-examples.json` to make examples available via `smithy init` command
---
> Add documentation for smithy-trait-package plugin

- smithy-base/src/main/java/software/amazon/smithy/gradle/tasks/SmithyValidateTask.java
Updates the minimum severity for logging in validate task to `DANGER` as unsuppressed DANGER events can still cause the validation to fail. 
---
> Update minimum log severity for smithy validate task

- .github/workflows/ci.yml
* The CI for this repo pulls the smithy repo locally and builds it
* However, the smithy repo only supports builds on JDK17 and above 
* Removes 8 and 11 builds
* https://github.com/smithy-lang/smithy/pull/2487
---
> Remove JDK 8, 11 from CI

- smithy-base/src/main/java/software/amazon/smithy/gradle/internal/CliDependencyResolver.java
- As discovered in https://github.com/smithy-lang/smithy-java/pull/583, enforcing projects in the smithy repository to explicitly depend on the CLI has the unintended consequence of bringing it into the runtime classpath
- This change makes it so that the plugin will automatically add the cli as a project dependency if the plugin is used within a main smithy project
---
> Use smithy-cli as project dependency when plugin used within smithy

- smithy-base/src/main/java/software/amazon/smithy/gradle/SmithyBasePlugin.java
- smithy-jar/src/main/java/software/amazon/smithy/gradle/SmithyJarPlugin.java
- These tasks do not declare any outputs, therefore they are never considered up-to-date by gradle
- This change adds dummy outputs to these tasks
- The real outputs are the same as the inputs, but marking the inputs as outputs becomes problematic when there are cross-project task dependencies 
- Create a project that uses the smithy jar plugin
- Use a maven-local version, and run pTML with these changes
- Run `smithyValidate -i`, verify it (and `smithyFormat`) runs
- Run `smithyValidate -i` again, verify it (and `smithyFormat`) is marked up-to-date and not re-ran
* Links to additional context, if necessary
* Issue #, if applicable (see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keywo …
> Declare task output for validate and format tasks so they are incremental
